apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-todo
  name: flask-todo
  namespace: flask-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-todo
  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      containers:
      - image: quay.io/mregan/flask-todo-ma:v0.1
        name: flask-todo
      ports:
      - containerPort: 8080
