apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: flask-todo
spec:
  host: flask-todo-openshift-flask-todo.apps.snocone.test-cluster.redhat.lan
  port:
    targetPort: 80
  to:
    kind: Service
    name: flask-todo
    weight: 100
status:
  ingress: []
